LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
LOCAL_CFLAGS := -Os

openssl_path := $(openssl_path)../../../../external/openssl/crypto/

ifeq ($(TARGET_ARCH),arm)
	LOCAL_CFLAGS += -DOPENSSL_BN_ASM_MONT -DAES_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM
	LOCAL_SRC_FILES:= $(openssl_path)0.9.9-dev/bn/armv4-mont.s \
	                  $(openssl_path)0.9.9-dev/aes/aes-armv4.s \
	                  $(openssl_path)0.9.9-dev/sha/sha1-armv4-large.s \
	                  $(openssl_path)0.9.9-dev/sha/sha256-armv4.s \
	                  $(openssl_path)0.9.9-dev/sha/sha512-armv4.s
else
	LOCAL_SRC_FILES:= $(openssl_path)aes/aes_core.c
endif

ifeq ($(TARGET_SIMULATOR),true)
	# Make valgrind happy.
	LOCAL_CFLAGS += -DPURIFY
endif

LOCAL_SRC_FILES+= \
	$(openssl_path)cryptlib.c \
	$(openssl_path)mem.c \
	$(openssl_path)mem_clr.c \
	$(openssl_path)mem_dbg.c \
	$(openssl_path)cversion.c \
	$(openssl_path)dyn_lck.c \
	$(openssl_path)ex_data.c \
	$(openssl_path)tmdiff.c \
	$(openssl_path)cpt_err.c \
	$(openssl_path)ebcdic.c \
	$(openssl_path)uid.c \
	$(openssl_path)o_time.c \
	$(openssl_path)o_str.c \
	$(openssl_path)o_dir.c \
	$(openssl_path)aes/aes_misc.c \
	$(openssl_path)aes/aes_ecb.c \
	$(openssl_path)aes/aes_cbc.c \
	$(openssl_path)aes/aes_cfb.c \
	$(openssl_path)aes/aes_ofb.c \
	$(openssl_path)aes/aes_ctr.c \
	$(openssl_path)aes/aes_wrap.c \
	$(openssl_path)asn1/a_object.c \
	$(openssl_path)asn1/a_bitstr.c \
	$(openssl_path)asn1/a_utctm.c \
	$(openssl_path)asn1/a_gentm.c \
	$(openssl_path)asn1/a_time.c \
	$(openssl_path)asn1/a_int.c \
	$(openssl_path)asn1/a_octet.c \
	$(openssl_path)asn1/a_print.c \
	$(openssl_path)asn1/a_type.c \
	$(openssl_path)asn1/a_set.c \
	$(openssl_path)asn1/a_dup.c \
	$(openssl_path)asn1/a_d2i_fp.c \
	$(openssl_path)asn1/a_i2d_fp.c \
	$(openssl_path)asn1/a_enum.c \
	$(openssl_path)asn1/a_utf8.c \
	$(openssl_path)asn1/a_sign.c \
	$(openssl_path)asn1/a_digest.c \
	$(openssl_path)asn1/a_verify.c \
	$(openssl_path)asn1/a_mbstr.c \
	$(openssl_path)asn1/a_strex.c \
	$(openssl_path)asn1/x_algor.c \
	$(openssl_path)asn1/x_val.c \
	$(openssl_path)asn1/x_pubkey.c \
	$(openssl_path)asn1/x_sig.c \
	$(openssl_path)asn1/x_req.c \
	$(openssl_path)asn1/x_attrib.c \
	$(openssl_path)asn1/x_bignum.c \
	$(openssl_path)asn1/x_long.c \
	$(openssl_path)asn1/x_name.c \
	$(openssl_path)asn1/x_x509.c \
	$(openssl_path)asn1/x_x509a.c \
	$(openssl_path)asn1/x_crl.c \
	$(openssl_path)asn1/x_info.c \
	$(openssl_path)asn1/x_spki.c \
	$(openssl_path)asn1/nsseq.c \
	$(openssl_path)asn1/d2i_pu.c \
	$(openssl_path)asn1/d2i_pr.c \
	$(openssl_path)asn1/i2d_pu.c \
	$(openssl_path)asn1/i2d_pr.c \
	$(openssl_path)asn1/t_req.c \
	$(openssl_path)asn1/t_x509.c \
	$(openssl_path)asn1/t_x509a.c \
	$(openssl_path)asn1/t_crl.c \
	$(openssl_path)asn1/t_pkey.c \
	$(openssl_path)asn1/t_spki.c \
	$(openssl_path)asn1/t_bitst.c \
	$(openssl_path)asn1/tasn_new.c \
	$(openssl_path)asn1/tasn_fre.c \
	$(openssl_path)asn1/tasn_enc.c \
	$(openssl_path)asn1/tasn_dec.c \
	$(openssl_path)asn1/tasn_utl.c \
	$(openssl_path)asn1/tasn_typ.c \
	$(openssl_path)asn1/f_int.c \
	$(openssl_path)asn1/f_string.c \
	$(openssl_path)asn1/n_pkey.c \
	$(openssl_path)asn1/f_enum.c \
	$(openssl_path)asn1/a_hdr.c \
	$(openssl_path)asn1/x_pkey.c \
	$(openssl_path)asn1/a_bool.c \
	$(openssl_path)asn1/x_exten.c \
	$(openssl_path)asn1/asn1_par.c \
	$(openssl_path)asn1/asn1_lib.c \
	$(openssl_path)asn1/asn1_err.c \
	$(openssl_path)asn1/a_meth.c \
	$(openssl_path)asn1/a_bytes.c \
	$(openssl_path)asn1/a_strnid.c \
	$(openssl_path)asn1/evp_asn1.c \
	$(openssl_path)asn1/asn_pack.c \
	$(openssl_path)asn1/p5_pbe.c \
	$(openssl_path)asn1/p5_pbev2.c \
	$(openssl_path)asn1/p8_pkey.c \
	$(openssl_path)asn1/asn_moid.c \
	$(openssl_path)asn1/asn1_gen.c \
	$(openssl_path)asn1/asn_mime.c \
	$(openssl_path)bio/bio_lib.c \
	$(openssl_path)bio/bio_cb.c \
	$(openssl_path)bio/bio_err.c \
	$(openssl_path)bio/bss_mem.c \
	$(openssl_path)bio/bss_null.c \
	$(openssl_path)bio/bss_fd.c \
	$(openssl_path)bio/bss_file.c \
	$(openssl_path)bio/bss_sock.c \
	$(openssl_path)bio/bss_conn.c \
	$(openssl_path)bio/bf_null.c \
	$(openssl_path)bio/bf_buff.c \
	$(openssl_path)bio/b_print.c \
	$(openssl_path)bio/b_dump.c \
	$(openssl_path)bio/b_sock.c \
	$(openssl_path)bio/bss_acpt.c \
	$(openssl_path)bio/bf_nbio.c \
	$(openssl_path)bio/bss_log.c \
	$(openssl_path)bio/bss_bio.c \
	$(openssl_path)bio/bss_dgram.c \
	$(openssl_path)bn/bn_add.c \
	$(openssl_path)bn/bn_div.c \
	$(openssl_path)bn/bn_exp.c \
	$(openssl_path)bn/bn_lib.c \
	$(openssl_path)bn/bn_ctx.c \
	$(openssl_path)bn/bn_mul.c \
	$(openssl_path)bn/bn_mod.c \
	$(openssl_path)bn/bn_opt.c \
	$(openssl_path)bn/bn_print.c \
	$(openssl_path)bn/bn_rand.c \
	$(openssl_path)bn/bn_shift.c \
	$(openssl_path)bn/bn_word.c \
	$(openssl_path)bn/bn_blind.c \
	$(openssl_path)bn/bn_kron.c \
	$(openssl_path)bn/bn_sqrt.c \
	$(openssl_path)bn/bn_gcd.c \
	$(openssl_path)bn/bn_prime.c \
	$(openssl_path)bn/bn_err.c \
	$(openssl_path)bn/bn_sqr.c \
	$(openssl_path)bn/bn_asm.c \
	$(openssl_path)bn/bn_recp.c \
	$(openssl_path)bn/bn_mont.c \
	$(openssl_path)bn/bn_mpi.c \
	$(openssl_path)bn/bn_exp2.c \
	$(openssl_path)bn/bn_nist.c \
	$(openssl_path)bn/bn_gf2m.c \
	$(openssl_path)bn/bn_x931p.c \
	$(openssl_path)buffer/buffer.c \
	$(openssl_path)buffer/buf_err.c \
	$(openssl_path)buffer/buf_str.c \
	$(openssl_path)comp/comp_lib.c \
	$(openssl_path)comp/comp_err.c \
	$(openssl_path)comp/c_rle.c \
	$(openssl_path)comp/c_zlib.c \
	$(openssl_path)conf/conf_err.c \
	$(openssl_path)conf/conf_lib.c \
	$(openssl_path)conf/conf_api.c \
	$(openssl_path)conf/conf_def.c \
	$(openssl_path)conf/conf_mod.c \
	$(openssl_path)conf/conf_mall.c \
	$(openssl_path)conf/conf_sap.c \
	$(openssl_path)des/cbc_cksm.c \
	$(openssl_path)des/cbc_enc.c \
	$(openssl_path)des/cfb64enc.c \
	$(openssl_path)des/cfb_enc.c \
	$(openssl_path)des/des_lib.c \
	$(openssl_path)des/ecb3_enc.c \
	$(openssl_path)des/ecb_enc.c \
	$(openssl_path)des/enc_read.c \
	$(openssl_path)des/enc_writ.c \
	$(openssl_path)des/fcrypt.c \
	$(openssl_path)des/ofb64enc.c \
	$(openssl_path)des/ofb_enc.c \
	$(openssl_path)des/pcbc_enc.c \
	$(openssl_path)des/qud_cksm.c \
	$(openssl_path)des/rand_key.c \
	$(openssl_path)des/rpc_enc.c \
	$(openssl_path)des/set_key.c \
	$(openssl_path)des/des_enc.c \
	$(openssl_path)des/fcrypt_b.c \
	$(openssl_path)des/xcbc_enc.c \
	$(openssl_path)des/str2key.c \
	$(openssl_path)des/cfb64ede.c \
	$(openssl_path)des/ofb64ede.c \
	$(openssl_path)des/ede_cbcm_enc.c \
	$(openssl_path)des/des_old.c \
	$(openssl_path)des/des_old2.c \
	$(openssl_path)des/read2pwd.c \
	$(openssl_path)dso/dso_dl.c \
	$(openssl_path)dso/dso_dlfcn.c \
	$(openssl_path)dso/dso_err.c \
	$(openssl_path)dso/dso_lib.c \
	$(openssl_path)dso/dso_null.c \
	$(openssl_path)dso/dso_openssl.c \
	$(openssl_path)dso/dso_win32.c \
	$(openssl_path)dso/dso_vms.c \
	$(openssl_path)err/err.c \
	$(openssl_path)err/err_bio.c \
	$(openssl_path)err/err_def.c \
	$(openssl_path)err/err_all.c \
	$(openssl_path)err/err_prn.c \
	$(openssl_path)err/err_str.c \
	$(openssl_path)evp/encode.c \
	$(openssl_path)evp/digest.c \
	$(openssl_path)evp/enc_min.c \
	$(openssl_path)evp/evp_cnf.c \
	$(openssl_path)evp/evp_enc.c \
	$(openssl_path)evp/evp_key.c \
	$(openssl_path)evp/evp_acnf.c \
	$(openssl_path)evp/e_des.c \
	$(openssl_path)evp/e_des3.c \
	$(openssl_path)evp/e_rc4.c \
	$(openssl_path)evp/e_aes.c \
	$(openssl_path)evp/names.c \
	$(openssl_path)evp/e_xcbc_d.c \
	$(openssl_path)evp/e_rc2.c \
	$(openssl_path)evp/e_rc5.c \
	$(openssl_path)evp/m_null.c \
	$(openssl_path)evp/m_md2.c \
	$(openssl_path)evp/m_md4.c \
	$(openssl_path)evp/m_md5.c \
	$(openssl_path)evp/m_sha.c \
	$(openssl_path)evp/m_sha1.c \
	$(openssl_path)evp/m_dss.c \
	$(openssl_path)evp/m_dss1.c \
	$(openssl_path)evp/m_mdc2.c \
	$(openssl_path)evp/p_open.c \
	$(openssl_path)evp/p_seal.c \
	$(openssl_path)evp/p_sign.c \
	$(openssl_path)evp/p_verify.c \
	$(openssl_path)evp/p_lib.c \
	$(openssl_path)evp/p_enc.c \
	$(openssl_path)evp/p_dec.c \
	$(openssl_path)evp/bio_md.c \
	$(openssl_path)evp/bio_b64.c \
	$(openssl_path)evp/bio_enc.c \
	$(openssl_path)evp/evp_err.c \
	$(openssl_path)evp/e_null.c \
	$(openssl_path)evp/c_all.c \
	$(openssl_path)evp/c_allc.c \
	$(openssl_path)evp/c_alld.c \
	$(openssl_path)evp/evp_lib.c \
	$(openssl_path)evp/bio_ok.c \
	$(openssl_path)evp/evp_pkey.c \
	$(openssl_path)evp/evp_pbe.c \
	$(openssl_path)evp/p5_crpt.c \
	$(openssl_path)evp/p5_crpt2.c \
	$(openssl_path)evp/e_old.c \
	$(openssl_path)hmac/hmac.c \
	$(openssl_path)krb5/krb5_asn.c \
	$(openssl_path)lhash/lhash.c \
	$(openssl_path)lhash/lh_stats.c \
	$(openssl_path)md4/md4_dgst.c \
	$(openssl_path)md4/md4_one.c \
	$(openssl_path)md5/md5_dgst.c \
	$(openssl_path)md5/md5_one.c \
	$(openssl_path)objects/o_names.c \
	$(openssl_path)objects/obj_dat.c \
	$(openssl_path)objects/obj_lib.c \
	$(openssl_path)objects/obj_err.c \
	$(openssl_path)ocsp/ocsp_asn.c \
	$(openssl_path)ocsp/ocsp_cl.c \
	$(openssl_path)ocsp/ocsp_err.c \
	$(openssl_path)ocsp/ocsp_ext.c \
	$(openssl_path)ocsp/ocsp_ht.c \
	$(openssl_path)ocsp/ocsp_lib.c \
	$(openssl_path)ocsp/ocsp_prn.c \
	$(openssl_path)ocsp/ocsp_srv.c \
	$(openssl_path)ocsp/ocsp_vfy.c \
	$(openssl_path)pem/pem_sign.c \
	$(openssl_path)pem/pem_seal.c \
	$(openssl_path)pem/pem_info.c \
	$(openssl_path)pem/pem_lib.c \
	$(openssl_path)pem/pem_all.c \
	$(openssl_path)pem/pem_err.c \
	$(openssl_path)pem/pem_x509.c \
	$(openssl_path)pem/pem_xaux.c \
	$(openssl_path)pem/pem_oth.c \
	$(openssl_path)pem/pem_pk8.c \
	$(openssl_path)pem/pem_pkey.c \
	$(openssl_path)pkcs12/p12_add.c \
	$(openssl_path)pkcs12/p12_asn.c \
	$(openssl_path)pkcs12/p12_attr.c \
	$(openssl_path)pkcs12/p12_crpt.c \
	$(openssl_path)pkcs12/p12_crt.c \
	$(openssl_path)pkcs12/p12_decr.c \
	$(openssl_path)pkcs12/p12_init.c \
	$(openssl_path)pkcs12/p12_key.c \
	$(openssl_path)pkcs12/p12_kiss.c \
	$(openssl_path)pkcs12/p12_mutl.c \
	$(openssl_path)pkcs12/p12_utl.c \
	$(openssl_path)pkcs12/p12_npas.c \
	$(openssl_path)pkcs12/pk12err.c \
	$(openssl_path)pkcs12/p12_p8d.c \
	$(openssl_path)pkcs12/p12_p8e.c \
	$(openssl_path)pkcs7/pk7_asn1.c \
	$(openssl_path)pkcs7/pk7_lib.c \
	$(openssl_path)pkcs7/pkcs7err.c \
	$(openssl_path)pkcs7/pk7_doit.c \
	$(openssl_path)pkcs7/pk7_smime.c \
	$(openssl_path)pkcs7/pk7_attr.c \
	$(openssl_path)pkcs7/pk7_mime.c \
	$(openssl_path)rand/md_rand.c \
	$(openssl_path)rand/randfile.c \
	$(openssl_path)rand/rand_lib.c \
	$(openssl_path)rand/rand_err.c \
	$(openssl_path)rand/rand_egd.c \
	$(openssl_path)rand/rand_unix.c \
	$(openssl_path)rc2/rc2_ecb.c \
	$(openssl_path)rc2/rc2_skey.c \
	$(openssl_path)rc2/rc2_cbc.c \
	$(openssl_path)rc2/rc2cfb64.c \
	$(openssl_path)rc2/rc2ofb64.c \
	$(openssl_path)rc4/rc4_skey.c \
	$(openssl_path)rc4/rc4_enc.c \
	$(openssl_path)rsa/rsa_x931g.c \
	$(openssl_path)rsa/rsa_eay.c \
	$(openssl_path)rsa/rsa_eng.c \
	$(openssl_path)rsa/rsa_gen.c \
	$(openssl_path)rsa/rsa_lib.c \
	$(openssl_path)rsa/rsa_sign.c \
	$(openssl_path)rsa/rsa_saos.c \
	$(openssl_path)rsa/rsa_err.c \
	$(openssl_path)rsa/rsa_pk1.c \
	$(openssl_path)rsa/rsa_ssl.c \
	$(openssl_path)rsa/rsa_none.c \
	$(openssl_path)rsa/rsa_oaep.c \
	$(openssl_path)rsa/rsa_chk.c \
	$(openssl_path)rsa/rsa_null.c \
	$(openssl_path)rsa/rsa_pss.c \
	$(openssl_path)rsa/rsa_x931.c \
	$(openssl_path)rsa/rsa_asn1.c \
	$(openssl_path)sha/sha_dgst.c \
	$(openssl_path)sha/sha1dgst.c \
	$(openssl_path)sha/sha_one.c \
	$(openssl_path)sha/sha1_one.c \
	$(openssl_path)sha/sha256.c \
	$(openssl_path)sha/sha512.c \
	$(openssl_path)stack/stack.c \
	$(openssl_path)txt_db/txt_db.c \
	$(openssl_path)ui/ui_err.c \
	$(openssl_path)ui/ui_lib.c \
	$(openssl_path)ui/ui_openssl.c \
	$(openssl_path)ui/ui_util.c \
	$(openssl_path)ui/ui_compat.c \
	$(openssl_path)x509/x509_def.c \
	$(openssl_path)x509/x509_d2.c \
	$(openssl_path)x509/x509_r2x.c \
	$(openssl_path)x509/x509_cmp.c \
	$(openssl_path)x509/x509_obj.c \
	$(openssl_path)x509/x509_req.c \
	$(openssl_path)x509/x509spki.c \
	$(openssl_path)x509/x509_vfy.c \
	$(openssl_path)x509/x509_set.c \
	$(openssl_path)x509/x509cset.c \
	$(openssl_path)x509/x509rset.c \
	$(openssl_path)x509/x509_err.c \
	$(openssl_path)x509/x509name.c \
	$(openssl_path)x509/x509_v3.c \
	$(openssl_path)x509/x509_ext.c \
	$(openssl_path)x509/x509_att.c \
	$(openssl_path)x509/x509_vpm.c \
	$(openssl_path)x509/x509type.c \
	$(openssl_path)x509/x509_lu.c \
	$(openssl_path)x509/x_all.c \
	$(openssl_path)x509/x509_txt.c \
	$(openssl_path)x509/x509_trs.c \
	$(openssl_path)x509/by_file.c \
	$(openssl_path)x509/by_dir.c \
	$(openssl_path)x509v3/v3_bcons.c \
	$(openssl_path)x509v3/v3_bitst.c \
	$(openssl_path)x509v3/v3_conf.c \
	$(openssl_path)x509v3/v3_extku.c \
	$(openssl_path)x509v3/v3_ia5.c \
	$(openssl_path)x509v3/v3_lib.c \
	$(openssl_path)x509v3/v3_prn.c \
	$(openssl_path)x509v3/v3_utl.c \
	$(openssl_path)x509v3/v3err.c \
	$(openssl_path)x509v3/v3_genn.c \
	$(openssl_path)x509v3/v3_alt.c \
	$(openssl_path)x509v3/v3_skey.c \
	$(openssl_path)x509v3/v3_akey.c \
	$(openssl_path)x509v3/v3_pku.c \
	$(openssl_path)x509v3/v3_int.c \
	$(openssl_path)x509v3/v3_enum.c \
	$(openssl_path)x509v3/v3_sxnet.c \
	$(openssl_path)x509v3/v3_cpols.c \
	$(openssl_path)x509v3/v3_crld.c \
	$(openssl_path)x509v3/v3_purp.c \
	$(openssl_path)x509v3/v3_info.c \
	$(openssl_path)x509v3/v3_akeya.c \
	$(openssl_path)x509v3/v3_ocsp.c \
	$(openssl_path)x509v3/v3_pcia.c \
	$(openssl_path)x509v3/v3_pci.c \
	$(openssl_path)x509v3/v3_pmaps.c \
	$(openssl_path)x509v3/v3_pcons.c \
	$(openssl_path)x509v3/v3_ncons.c \
	$(openssl_path)x509v3/pcy_lib.c \
	$(openssl_path)x509v3/pcy_cache.c \
	$(openssl_path)x509v3/pcy_node.c \
	$(openssl_path)x509v3/pcy_map.c \
	$(openssl_path)x509v3/pcy_data.c \
	$(openssl_path)x509v3/pcy_tree.c \
	$(openssl_path)dh/dh_asn1.c \
	$(openssl_path)dh/dh_check.c \
	$(openssl_path)dh/dh_depr.c \
	$(openssl_path)dh/dh_err.c \
	$(openssl_path)dh/dh_gen.c \
	$(openssl_path)dh/dh_key.c \
	$(openssl_path)dh/dh_lib.c \
	$(openssl_path)dsa/dsa_asn1.c \
	$(openssl_path)dsa/dsa_depr.c \
	$(openssl_path)dsa/dsa_err.c \
	$(openssl_path)dsa/dsa_gen.c \
	$(openssl_path)dsa/dsa_key.c \
	$(openssl_path)dsa/dsa_lib.c \
	$(openssl_path)dsa/dsa_ossl.c \
	$(openssl_path)dsa/dsa_sign.c \
	$(openssl_path)dsa/dsa_utl.c \
	$(openssl_path)dsa/dsa_vrf.c \
	$(openssl_path)ripemd/rmd_dgst.c \
	$(openssl_path)ripemd/rmd_one.c \
	$(openssl_path)evp/m_ripemd.c

LOCAL_CFLAGS += -DNO_WINDOWS_BRAINDEATH

include $(LOCAL_PATH)/android-config.mk

LOCAL_C_INCLUDES += \
	external/openssl \
	external/openssl/crypto \
	external/openssl/include \
	external/zlib

LOCAL_STATIC_LIBRARIES += libz

ifneq ($(TARGET_SIMULATOR),true)
	LOCAL_STATIC_LIBRARIES += libdl
endif

LOCAL_LDLIBS += -ldl

LOCAL_MODULE:= libsteam_crypto

include $(BUILD_STATIC_LIBRARY)
